"""empty message

Revision ID: 5792aad13891
Revises: None
Create Date: 2015-04-29 11:15:23.106000

"""

# revision identifiers, used by Alembic.
revision = '5792aad13891'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('flag', sa.INTEGER(), nullable=True))
    op.create_index(op.f('ix_datasets_website'), 'datasets', ['website'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datasets_website'), table_name='datasets')
    op.drop_column('datasets', 'flag')
    ### end Alembic commands ###
